name: mastodon_dart
description: The unofficial Mastodon client
version: 0.3.2
homepage: https://github.com/lukepighetti/mastodon_dart

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.4.0
  rxdart: ^0.27.3
  web_socket_channel: ^2.1.0
  async: ^2.9.0

dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  lints: ^1.0.1
  stack_trace: ^1.10.0
  test: ^1.21.1
