name: mastodon_dart
description: The unofficial Mastodon client
version: 1.0.0
homepage: https://github.com/lukepighetti/mastodon_dart

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  http: ^0.13.5
  json_annotation: ^4.7.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.1
  test: ^1.22.0
