name: main

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: task get
      - run: task analyze

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: task gen
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated files
          file_pattern: "*.g.dart"

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: task format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update formatted files
          file_pattern: "*.dart"
